//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClimateControl.Web.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SensorData
    {
        public int Id { get; set; }
        public string deviceId { get; set; }
        [DisplayFormat(DataFormatString = "{0:0.00}")]
        public double temperature { get; set; }
        [DisplayFormat(DataFormatString = "{0:F1}")]
        public double humidity { get; set; }
        public double co2 { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy HH:MM:ss}")]
        public System.DateTime EventProcessedUtcTime { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy HH:MM:ss}")]
        public System.DateTime EventEnqueuedUtcTime { get; set; }
    }
}
