//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClimateControl.Web.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SensorData
    {
        public int Id { get; set; }
        [Display(Name = "Device name")]
        public string deviceId { get; set; }
        [DisplayFormat(DataFormatString = "{0:0.00}")]
        [Display(Name = "Temperature,C")]
        public double temperature { get; set; }
        [DisplayFormat(DataFormatString = "{0:F1}")]
        [Display(Name = "Humidity,%")]
        public double humidity { get; set; }
        [Display(Name = "CO2")]
        public double co2 { get; set; }
        [Display(Name = "Time Processed")]        
        public System.DateTime EventProcessedUtcTime { get; set; }
        [Display(Name = "Time Enqueued")]        
        public System.DateTime EventEnqueuedUtcTime { get; set; }
    }
}
